import { StyleSheet } from "react-native";

export const colors = {
  primary: "#059669",
  primaryDark: "#047857",
  primarySoft: "#ecfdf5",
  bg: "#f1f5f9",
  card: "#ffffff",
  text: "#1e293b",
  // slate-500: contraste 4.76:1 sobre branco (o antigo #94a3b8 reprovava WCAG)
  muted: "#64748b",
  mutedSoft: "#94a3b8",
  border: "#e2e8f0",
  danger: "#dc2626",
  dangerSoft: "#fef2f2",
  warn: "#b45309",
  warnBg: "#fef3c7",
};

export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  container: { padding: 16, gap: 12 },
  card: {
    backgroundColor: colors.card,
    borderRadius: 14,
    padding: 14,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  cardTitle: { fontSize: 13, fontWeight: "600", color: colors.muted, marginBottom: 8 },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    gap: 8,
  },
  divider: { height: StyleSheet.hairlineWidth, backgroundColor: colors.border },
  h1: { fontSize: 20, fontWeight: "700", color: colors.text },
  label: { fontSize: 12, fontWeight: "600", color: colors.muted, marginBottom: 4 },
  input: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.text,
  },
  button: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    minHeight: 48, // alvo de toque mínimo (Apple HIG: 44pt)
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minHeight: 36,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { fontSize: 13, color: colors.text },
  chipTextActive: { color: "#fff", fontWeight: "600" },
  /** ação pequena de lista (Pagar) com área de toque adequada */
  listAction: {
    minHeight: 36,
    minWidth: 56,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#a7f3d0",
    backgroundColor: colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  listActionText: { color: colors.primaryDark, fontWeight: "700", fontSize: 13 },
  /** círculo de ícone para direção do lançamento */
  iconCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  money: { fontVariant: ["tabular-nums"], fontWeight: "600" },
  emptyText: { textAlign: "center", color: colors.muted, paddingVertical: 20, fontSize: 13 },
  emptyBox: { alignItems: "center", gap: 6, paddingVertical: 20 },
});
